title: "<The item you want to talk about>"
body:
  - type: markdown
    attributes: 
      value: |
        If you want to ask for a feature, please use the [Feature Requests GitHub Discussions](https://github.com/NW-PaGe/discussions/categories/feature-requests).
        If you want to ask for help, please use the [Q&A GitHub Discussions](https://github.com/NW-PaGe/discussions/categories/q-a).
  - type: textarea
    attributes:
      label: Description
      description: Describe your item!
    validations:
      required: true
  - type: markdown
    attributes:
      value: "_Thanks for using our Github page!_"
